spendapp/config/routes.rb
Spendapp::Application.routes.draw do
  resources :sprojects

  resources :projects do as_routes 
end
  devise_for :users do
end

 

  root :to=> 'pages#home'
  get 'memberhome' => 'pages#memberhome'

end

spendapp/app/models/sproject.rb
class Sproject < ActiveRecord::Base
  attr_accessible :amtremaining, :budget, :date, :name, :note, :spend
  validates :name, :budget, presence: true

  belongs_to :user
  validates :user_id, presence: true
end

spendapp/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :sprojects
end

spendapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

spendapp/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def memberhome
  end
end

spendapp/app/controllers/sprojects_controller.rb
class SprojectsController < ApplicationController
  before_filter :authenticate_user!

  # GET /sprojects
  # GET /sprojects.json
  def index
    @sprojects = current_user.sprojects.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sprojects }
    end
  end

  # GET /sprojects/1
  # GET /sprojects/1.json
  def show
    @sproject = current_user.sprojects.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sproject }
    end
  end

  # GET /sprojects/new
  # GET /sprojects/new.json
  def new
    @sproject = current_user.sprojects.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sproject }
    end
  end

  # GET /sprojects/1/edit
  def edit
    @sproject = current_user.sprojects.find(params[:id])
  end

  # POST /sprojects
  # POST /sprojects.json
  def create
    @sproject = current_user.sprojects.new(params[:sproject])

    respond_to do |format|
      if @sproject.save
        format.html { redirect_to @sproject, notice: 'Sproject was successfully created.' }
        format.json { render json: @sproject, status: :created, location: @sproject }
      else
        format.html { render action: "new" }
        format.json { render json: @sproject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sprojects/1
  # PUT /sprojects/1.json
  def update
    @sproject = current_user.sprojects.find(params[:id])

    respond_to do |format|
      if @sproject.update_attributes(params[:sproject])
        format.html { redirect_to @sproject, notice: 'Sproject was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sproject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sprojects/1
  # DELETE /sprojects/1.json
  def destroy
    @sproject = current_user.sprojects.find(params[:id])
    @sproject.destroy

    respond_to do |format|
      format.html { redirect_to sprojects_url }
      format.json { head :no_content }
    end
  end
end

spendapp/app/helpers/application_helper.rb
module ApplicationHelper
end

spendapp/app/helpers/models_helper.rb
module ModelsHelper
end

spendapp/app/helpers/pages_helper.rb
module PagesHelper
end

spendapp/app/helpers/sprojects_helper.rb
module SprojectsHelper
end

spendapp/app/views/layouts/_footer.html.erb
<div class="footer">
	<blockquote class="pull-right">
	  <small>Copyright 2014 by <%= link_to "LiteMind Group, Inc.", "http://litemindgroup.com" %></small>
	</blockquote>
</div>


spendapp/app/views/layouts/_header.html.erb
<div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Brand</a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "Home", root_path %></li>
            <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li class="dropdown-header">Dropdown header</li>
          <li><a href="#">Separated link</a></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
    </ul>
    <form class="navbar-form navbar-left">
      <input type="text" class="form-control col-lg-8" placeholder="Search">
    </form>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div>

spendapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Spendworthy</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>

		<div class="container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>
		</div>
		<%= yield %>

		<%= render 'layouts/footer' %>	

	</body>
</html>

spendapp/app/views/pages/home.html.erb
<div class="jumbotron">
	<% if user_signed_in? %>
		<h2 align="center">Spendworthy</h2>
		<h1 align="center"><%= link_to "Let's set up a new project!", new_sproject_path %></h1>
		<h3 align="center">or</h3>
		<h1 align="center"><%= link_to "Go to your project now", sprojects_path %></h1> 
	<% else %>
  	<h1 align="center">Spendworthy</h1>
	  <p align="center">It's time to decide if that trinket is worth your money.</p>
	  <h2 align="center">Is it <em> spendworthy? </em></h4>
	  <p align="center"><%= link_to "Sign Me Up", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
		<div class="col-md-3">
			<div class="panel panel-info">
			  <div class="panel-heading">
			    <h3 class="panel-title">Panel info</h3>
			  </div>
			  <div class="panel-body">
			    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			  </div>
			</div>
		</div>

		<div class="col-md-1">
		</div>

		<div class="col-md-3">
			<div class="panel panel-info">
			  <div class="panel-heading">
			    <h3 class="panel-title">Panel info</h3>
			  </div>
			  <div class="panel-body">
			    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			  </div>
			</div>
		</div>

		<div class="col-md-1">
		</div>

		<div class="col-md-3">
			<div class="panel panel-info">
			  <div class="panel-heading">
			    <h3 class="panel-title">Panel info</h3>
			  </div>
			  <div class="panel-body">
			    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			  </div>
			</div>
		</div>
<% end %>
</div>

spendapp/app/views/pages/memberhome.html.erb
<html>
<p>Welcome <%= @email %>!</p>

<% if new_existing_projects? %>
	<p>Let's set up that bucket o' cash!</p>

	<p><%= link_to 'Set it up', projectssetup_path %> %></p>
<% else %>

<%end%>
</html>

spendapp/app/views/sprojects/_form.html.erb
<%= form_for(@sproject) do |f| %>
  <% if @sproject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sproject.errors.count, "error") %> prohibited this sproject from being saved:</h2>

      <ul>
      <% @sproject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :budget %><br />
    <%= f.text_field :budget %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :spend %><br />
    <%= f.text_field :spend %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :amtremaining %><br />
    <%= f.text_field :amtremaining %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

spendapp/app/views/sprojects/edit.html.erb
<h1>Editing sproject</h1>

<%= render 'form' %>

<%= link_to 'Show', @sproject %> |
<%= link_to 'Back', sprojects_path %>

spendapp/app/views/sprojects/index.html.erb
<h1>Listing sprojects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Budget</th>
    <th>Date</th>
    <th>Spend</th>
    <th>Note</th>
    <th>Amtremaining</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sprojects.each do |sproject| %>
  <tr>
    <td><%= sproject.name %></td>
    <td><%= sproject.budget %></td>
    <td><%= sproject.date %></td>
    <td><%= sproject.spend %></td>
    <td><%= sproject.note %></td>
    <td><%= sproject.amtremaining %></td>
    <td><%= link_to 'Show', sproject %></td>
    <td><%= link_to 'Edit', edit_sproject_path(sproject) %></td>
    <td><%= link_to 'Destroy', sproject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sproject', new_sproject_path %>

spendapp/app/views/sprojects/new.html.erb
<h1>New sproject</h1>

<%= render 'form' %>

<%= link_to 'Back', sprojects_path %>

spendapp/app/views/sprojects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sproject.name %>
</p>

<p>
  <b>Budget:</b>
  <%= @sproject.budget %>
</p>

<p>
  <b>Date:</b>
  <%= @sproject.date %>
</p>

<p>
  <b>Spend:</b>
  <%= @sproject.spend %>
</p>

<p>
  <b>Note:</b>
  <%= @sproject.note %>
</p>

<p>
  <b>Amtremaining:</b>
  <%= @sproject.amtremaining %>
</p>


<%= link_to 'Edit', edit_sproject_path(@sproject) %> |
<%= link_to 'Back', sprojects_path %>